package com.vilt.talentos.dto;

import com.vilt.talentos.entity.DomainStatus;
import com.vilt.talentos.entity.RegistrationStatus;
import com.vilt.talentos.entity.ResourceStatus;
import com.vilt.talentos.entity.TechnicalProposalStatus;
import lombok.Builder;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Builder
public record ProfileResponse(
    UUID id,
    String name,
    String email,
    String groupName,
    String photoUrl,
    String cpf,
    String jobTitle,
    String area,
    String about,
    String allocationStatus,
    String careerPath,
    String level,
    String levelOverride,
    Integer levelScore,
    String levelJustification,
    Integer experienceYears,
    String registrationNumber,
    RegistrationStatus registrationStatus,
    ResourceStatus resourceStatus,
    LocalDate registrationRequestedAt,
    String registrationNotes,
    boolean hasClientMachine,
    String contractingArea,
    String costCenter,
    LocalDate projectEntryDate,
    Boolean billable,
    Boolean portoOnboarding,
    String projectManagerName,
    UUID allocationProjectId,
    String allocationProjectName,
    UUID allocationSquadId,
    String allocationSquadName,
    TechnicalProposalStatus technicalProposalStatus,
    String technicalProposalNumber,
    LocalDate technicalProposalSentAt,
    String technicalProposalNotes,
    List<ResourceEquipmentResponse> equipments,
    DomainStatus status,
    String contact,
    String contactEmail,
    String phone,
    String address,
    String postalCode,
    String cityState,
    String linkedinUrl,
    String githubUrl,
    List<ProfileSkillResponse> skills,
    Instant createdAt,
    Instant updatedAt
) {}
