ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS contato VARCHAR(200),
    ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS telefone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS endereco TEXT,
    ADD COLUMN IF NOT EXISTS cep VARCHAR(9),
    ADD COLUMN IF NOT EXISTS cidade_uf VARCHAR(100);
