ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS contact VARCHAR(200),
    ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(9),
    ADD COLUMN IF NOT EXISTS city_state VARCHAR(100);
